services:
  anki:
    platform: linux/amd64
    image: ghcr.io/adanato/obsidian_2_anki/anki-custom:latest
    container_name: anki-test
    environment:
      - PUID=1000
      - PGID=1000
      - ANKI_LANG=en
      - ANKI_VERSION=24.11
      - QT_QUICK_BACKEND=software
      - ANKI_NOHIGHDPI=1
    ports:
      - "3000:3000"
      - "8766:8765"
    volumes:
      - ./anki_data:/config
    shm_size: "1gb"
    restart: unless-stopped
